### ISSUE TITLE
Client does not halt after "contract balance is too low to pay" error

### ISSUE THREAD

**Issue by yaronvel** [SmartPool/smartpool-client#3]
I think it should stop.
In any case, please make sure it stops at least for other errors.

**Comment by tranvictor** [comment]
Introduce hot stop mode, SmartPool will exit immediately whenever it receives error returned by the Contract.
For kovan, we enable hot stop mode by default. The command line also has "--no-hot-stop" param to disable this mode.

Usage:
`./smartpool --keystore . --no-hot-stop`
