### ISSUE TITLE
Your SmartPool client is too old

### ISSUE THREAD

**Issue by marriva** [SmartPool/smartpool-client#54]
Your SmartPool client is too old. Please update to new version by going to https://github.com/SmartPool/smartpool-client.

`usr@ethereum:~/smartpool-client$ ./kovan_compile.sh`
`Install dependencies...`
`github.com/bmizerany/pat (download)`
`github.com/bmizerany/pat`
`Compiling SmartPool client...`
`Done. You can run SmartPool by ./kovan --help`
`usr@ethereum:~/smartpool-client$ ./kovan --keystore $HOME/.local/share/io.parity.ethereum/keys/kovan/ --miner 0x00724713c75f4Ee23b3e154f013C49616Eb00a44 --spcontract 0x0398ae5a974FE8179B6B0ab9baF4d5f366E932Bf`
`SmartPool is in Hot-Stop mode: It will exit immediately if the contract returns errors.`
`Using miner address: 0x00724713c75f4ee23b3e154f013c49616eb00a44`
`Connected to Ethereum node: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0`
`Using miner address: 0x00724713c75f4ee23b3e154f013c49616eb00a44`
`Please enter passphrase:`
`Unlocking account...Done.`
`Stat persister is running...`
`Couldn't load counter from storage. Initialize it to 0.`
`The address is already registered to the pool. Good to go.`
`Trying to set etherbase to SmartPool contract address: 0x0398ae5a974fe8179b6b0ab9baf4d5f366e932bf...Done.`
`Trying to set extradata to SmartPool extradata convention: SmartPool-WPc6TmiHwc429c40000000...Done.`
`peerCount: 18`
`The network is ready for mining.`
`Share collector is running...`
`Share persister and stat persister are running...`
`RPC Server is running...`
`You can start mining now by running ethminer using following command:`
`--------------------------`
`ethminer -F localhost:1633/:worker_name/`
`Change :worker_name to whichever name you want.`
`--------------------------`
`Saving stats to disk...Done.`
`Your SmartPool client is too old. Please update to new version by going to https://github.com/SmartPool/smartpool-client.`
`Persisting current state to disk...`
`Saving stats to disk...Done.`
`Gracefully stopped SmartPool.`
`usr@ethereum:~/smartpool-client$`

**Comment by tranvictor** [comment]
Hi @marriva , which branch of the client repo did you use? I can see that you are using out dated contract address so I assume you are using master branch. Please switch to use develop branch.

**Comment by marriva** [comment]
@tranvictor Hi

There is no cmd/kovan/main.go on develop branch

`usr@ethereum:~/smartpool-client$ ./kovan_compile.sh
Install dependencies...
Compiling SmartPool client...
stat cmd/kovan/main.go: no such file or directory
Error when executing command: 'build/env.sh go build -ldflags -s -o kovan cmd/kovan/main.go'
`

**Comment by tranvictor** [comment]
@marriva in develop branch, we dropped support for kovan because kovan is not relevant to what SmartPool does. With Kovan, there is not PoW mining.

On master, we had to mock a part of Smartpool to support Kovan because we couldn't launch SmartPool MVP version on Ropsten.

**Comment by marriva** [comment]
Ok I got it
