### ISSUE TITLE
Dead branches in repo

### ISSUE THREAD

**Issue by jcvernaleo** [SmartPool/smartpool-client#58]
This is mostly a housekeeping issue, but figured it is worth it anyway.

The following branches have been fully merged into master already and should really be deleted:
```
persist_shares
hotfix_issue19_compiling
issue18_check_coinbase
minimerkle_tree
gateway_param
duplicate_share
persist_timestamp
hotfix_submitter_hang
```

The following branches have already been merged into the `develop` branch and can therefore probably also be removed:
```
rigs_support
gas_price_param
persist_work
fix_concurrent_workpool
fix_issue_26
spps
mix_digest
tx_retry_with_higher_price
rig_ip
fix_40
log
tx_retry_on_public_node
web_interface
```

The only branches that are needed still are `produce_test_input`, `develop`, and of course `master`.

Of course if there is a good reason to keep them, then feel free to close this issue but I think it is easiest to keep track of what is still being worked on this way (and any branch that was merged as a PR is still available in the write-only origin/pr/# namespace).

**Comment by tranvictor** [comment]
Thanks John, I will remove them tmr. The idea is to maintain master as always a stable branch. Develop is a runnable branch. Any other branches are not stable, under on going development, allow break runs.

**Comment by jcvernaleo** [comment]
Yep, I'm totally happy for develop to be where work goes and then it only goes in to master when all is good (at release time more or less).  That's why all my PRs are targeting develop.

**Comment by jcvernaleo** [comment]
Looks like the old branches have been gone for a while so closing this.
